### ISSUE TITLE
Latest ROX seems to ignore saved settings.

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#103]
Compiled the version downloaded this morning. All directories open in a small window at the top left screen.  I have tried saving directory info using right click and middle click. Neither seems to work. Am I doing something wrong with the saving?
I am running it under IceWm and use the pinboard for desktop icons.

**Comment by jun7** [comment]
What is the `directory info'?

Recently I changed around icon size and it had bug awhile.
Newer version may solve it.

**Comment by jun7** [comment]
Ah, I confimed. Will fix it.

**Comment by frankzen** [comment]
OK Thanks

**Comment by jun7** [comment]
Commited
d66f8310520eaccb7bba7583d4fc90a3127fe7c8
Is fixed it?

**Comment by frankzen** [comment]
Yes, that appears to have fixed it. At least directories are opening the way they used to. Thanks

**Comment by jun7** [comment]
Thank you for reporting.
