### ISSUE TITLE
enhancement: don't flash item frame on mouse scroll over item count in toolbar

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#107]
I like the new "mouse scroll over item count in toolbar" feature! But I find a bit annoying that the item frame flashes for each item that gets selected. I think it would be better to just move the red underline without flashing each item. What do you think?

----

May I edit the [Changes](../wiki/Changes) wiki page and reword some entries - basically to describe a change more precisely with more words?

**Comment by jun7** [comment]
On my system it tells me where is cursor, but the cursor and blink is not same in various environment about colour or resolution.
So probably I will take it in the way changing around drawing.


>edit the Changes

Yes, it is not understandable even to me ;P

**Comment by jun7** [comment]
Ah, you are right. it annoys me now.

**Comment by step-** [comment]
I just reworded "Linked Windows" in wiki page "Changes".

**Comment by jun7** [comment]
Ah sorry I have a request that shorter is good, because long english drains us who haven't english skills.
