### ISSUE TITLE
enhancement: raise linked window to top without focus

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#108]
Currently the linked window opens without focus but below the current window. This is a problem when there isn't enough space for the linked window to fit between the current window and the screen edge. The linked window is partially below the current window - it can be almost completely covered, and it becomes useless at that point. If you could open the linked window _on top_, but still without focus, this problem would be mitigated. In most cases there would be no problem anymore.

**Comment by jun7** [comment]
Window behaviour is not cotrallable. Also it is different on each window manager.
Even current behaviour is on a tightrope and dropped in some cases ;P

**Comment by step-** [comment]
ok, thanks.
