### ISSUE TITLE
Wrong item sorting - folders and files mixed together

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#111]
Right after a reboot or after restarting X, when I open rox in `~`, folder and file items are mixed together in a single sorted list.  It shouldn't work that way, because I have "Options > Filer Windows > DIrectories come first (for sort by name)" enabled.
I think this option is ignored for **every new rox window that enters any new folder** - then the list mixes folder and file items together (bug). But if you back up one folder then **re-enter the same folder** the list displays folders first (correct). Trying moving up/down the same folder and you should see what I mean.

**Comment by jun7** [comment]
Confiremed, I will fix it.
thanks for the report.

**Comment by step-** [comment]
Compiled and tested here. Bug fix confirmed. Thank you!
