### ISSUE TITLE
Restore standard right-click behavior for folder items

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#112]
'Window Link' is a useful feature, however I use middle-click a lot to quickly open a folder, modify something inside it and close it (all of that having its parent window still open), so I prefer when the linked folder opens the new window right under my mouse pointer instead of to the side of the parent window. Perhaps you could make it so that right-clicking the icon opens to the side, and right-clicking the name/attributes opens under the mouse?

**Comment by jun7** [comment]
In that usage, why don't you use left click the dir?
I assigned rocker jesture to move parent dir for that usage.

**Comment by step-** [comment]
left click the dir opens opens the dir in same window. I want to open the dir in a new window that is positioned under the mouse pointer and not away from it to the side. Middle click to open folder in new window is standard rox behavior.
rocker jesture is a different usage: rocker jesture anywhere opens parent dir in current window, just like backspace key and toolbar up-arrow icon do.

**Comment by jun7** [comment]
And you close the window you said. So both result is a window of start dir. what is different?
Anyway, Window Link is an option. I don't think it is good for everyone. at least it needs wide monitor. So You can off it. Options > Filer windows > Window behaviour > Window Link.

**Comment by step-** [comment]
I close the window after I'm done working in it. The difference is the new window placement: under mouse vs to the side. It's a pity to have to disable window link to position new window under the mouse, window link is a useful feature.

**Comment by jun7** [comment]
1: window on A dir -> open new window of B dir -> close B dir -> result is A dir.
2: window on A dir -> change to B dir -> up to parent -> result is A dir.
So I can't get it why don't you pick the way 2?
the results are same, and case 2's window is under the mouse.

**Comment by step-** [comment]
1: window on A dir -> open new window of B dir -> _result window of B dir over window of A dir; work in B dir possibly dropping items from B onto A - easy, fast, work habit_
1.1 close B dir -> result is A dir; now work in A dir
2: window on A dir -> change to B dir -> _result is one window of B, there is no A to work with_
2.1 up to parent -> result is A dir. _but no work done between B and A (unless more mouse clicks to open and position A...)_

**Comment by jun7** [comment]
If you went to move a file B to A, drop the file to the up button. if you want B to A's sub dir, being side by side is good.

**Comment by step-** [comment]
But what if I want to drop a file from B to A/C/ ?

Anyway, we don't need to agree. With file managers there is no best way for doing things. We all have developed our specific habits and we are more comfortable with them. I'm fine if you don't think this change is worthwhile. You are the dev, you're in change. Thanks for discussing this issue, you can close it.

**Comment by step-** [comment]
Hi jun7, thanks for keeping this issue open as an enhancement request.
I have another example of middle-click to open folder. Assume folder structure /A/B  and /A/C, with A open in rox. You want to work between B and C. With middle-click (standard rox) it's easy: middle-click B then middle-click C. Now B and C are open - and A is also open under. You can work between B and C,  then close B and close C to find yourself in A again.
So I propose the following changes:

* middle-click folder icon: open folder over current folder
* shift-middle click folder: open folder in Linked Window

To me rolling over free toolbar space remains as the most convenient way to open Linked Windows.

**Comment by jun7** [comment]
Shift is assigned for another but ctrl is free may be. I will take it. thank you.

**Comment by step-** [comment]
Thank you for doing this. I compiled f8b72ef and it works well for me. With option Filer Windows > Window Behavior > Window Link disabled, m-click opens folder like standard ROX, and C-m-click opens linked window (or unlinks an already-open linked window). It's good, thank you again.
