### ISSUE TITLE
cosmetics

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#114]
Missing L, see screenshot.
Also, please can you tell me what those strange characters mean? I don't see them anywhere else in rox.

![screenshot](https://cloud.githubusercontent.com/assets/1414102/16163016/45d8a1a6-34d7-11e6-8291-b006446d3879.png)

**Comment by jun7** [comment]
It is in text of button. Come to think of it,  most rox's users using the Icon only of the Toolbar type. hm.
