### ISSUE TITLE
Change default color settings

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#122]
Commit 47dbb96d changed color defaults from
no alpha transparency, use background, background white
to
40% alpha transparency, use background, background black.
Below the left columns shows the default settings in compiz, jwm and openbox respectively. The second column shows the default settings but background color is set white.
It looks like the default settings aren't good for new users; black/blue labels are unreadable against the dark background.
Also, maybe enabling alpha transparency by default should be avoided.

![compiz-0](https://cloud.githubusercontent.com/assets/1414102/16294491/3e680cd8-3921-11e6-9faf-c7d4a2f167dd.png) ![compiz-1](https://cloud.githubusercontent.com/assets/1414102/16294493/3e68f904-3921-11e6-9005-d7d102c92446.png)

![jwm-0](https://cloud.githubusercontent.com/assets/1414102/16294494/3e6b65b8-3921-11e6-8c05-8685f91c9240.png) ![jwm-1](https://cloud.githubusercontent.com/assets/1414102/16294490/3e67d1be-3921-11e6-922c-9f690cbfcc09.png)

![ob-0](https://cloud.githubusercontent.com/assets/1414102/16294492/3e683c26-3921-11e6-9cbc-f692dcdb84e8.png) ![ob-1](https://cloud.githubusercontent.com/assets/1414102/16294489/3e676e72-3921-11e6-9da3-72e00dd4c76a.png)

**Comment by jun7** [comment]
I'm thinking of it.

**Comment by jun7** [comment]
Thanks for the report.

**Comment by step-** [comment]
Thank you for this change. There's still a small open issue. In options change default background color to \#FFFFFF. This is what gets written into file "Options"
```
  <Option name="background_colour">#fffffffffefe</Option>
```

**Comment by jun7** [comment]
I can't confirm it. Is there any step?

**Comment by step-** [comment]
Correction: change default color to \#FFFFFE for above. No special steps required. Perhaps it's due to machine architecture? I compile 64-bit version. 

----
![00](https://cloud.githubusercontent.com/assets/1414102/16404454/6e598b74-3cff-11e6-82fb-c849e19a174c.png)

----
![10](https://cloud.githubusercontent.com/assets/1414102/16404456/77136c6c-3cff-11e6-8dcc-52f285cb5bda.png)

----
![30](https://cloud.githubusercontent.com/assets/1414102/16404471/8eb8383e-3cff-11e6-9cf4-933ce8fb85e6.png)

----
![40](https://cloud.githubusercontent.com/assets/1414102/16404478/96ccff64-3cff-11e6-8d8d-ac5e9d96ed57.png)

**Comment by jun7** [comment]
I see. Because GdkColor's RGB is 16bit, then ffff every RGB is a natural.
It happens even standard rox.

**Comment by step-** [comment]
Hello, is this something that you could fix?

**Comment by step-** [comment]
No problem, sorry. I was confused.
