### ISSUE TITLE
background for jpeg thumbs from transparent png

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#123]
How can I set the default background color that is used to create JPG thumbnails? Currently it seems that the default background is black and cannot be changed (see screenshots).
Enhancement request: please allow setting the custom background to be used for the transparency channel when JPG thumbs are created.

Below you can see three cases:
1)  and 2) for jpeg thumbnails => black baground of mozilla.png and mtpaint.png icons => looks bad
3) png thumbails => alpha transparency => white (actual) background => looks good.

**1. JPG thumbs, NO use custom background, with actual background white:**
![00002](https://cloud.githubusercontent.com/assets/1414102/16297450/37c4e5f8-3931-11e6-96dc-0f6d3d18efd9.png)
![00003](https://cloud.githubusercontent.com/assets/1414102/16297449/37bd816e-3931-11e6-84d5-b2352c1a59e8.png)
![00004](https://cloud.githubusercontent.com/assets/1414102/16297448/37bacd7a-3931-11e6-9fa8-38cf573162c6.png)
**2. JPG thumbs, YES use custom background, with actual background white:**
![00005](https://cloud.githubusercontent.com/assets/1414102/16297447/37ba7bd6-3931-11e6-855d-85268c652c6e.png)
![00006](https://cloud.githubusercontent.com/assets/1414102/16297446/37ba7082-3931-11e6-9884-3335e125da9a.png)
**3. PNG thumbs, NO use custom background, with actual background white:**
![00007](https://cloud.githubusercontent.com/assets/1414102/16297445/37ba1bfa-3931-11e6-9b53-42d7cfc71d19.png)
![00008](https://cloud.githubusercontent.com/assets/1414102/16297451/37d1cab6-3931-11e6-8b7c-fc3180b787a2.png)

**Comment by jun7** [comment]
Jpeg hasn't alpha, so the black is may be set when created it.
And I noticed that viewing icons as thumbs not matches slower and larger six times.

**Comment by step-** [comment]
Yes, black is set when jpeg thumb is created. Question is: can you set another background color; take background color from options?

> And I noticed that viewing icons as thumbs not matches slower and larger six times.
But rox can't tell if png image file is for an icon or for a photo.

I think rox should create jpeg thumbs with current list background color to replace transparent pixels.

**Comment by jun7** [comment]
Ah sorry,  I misunderstood it. hm, I think it is too mush work though I'll keep it mind. thank you.

**Comment by jun7** [comment]
There is gdk_pixbuf_get_has_alpha. So I will take this.

**Comment by jun7** [comment]
I rethought of it, It has already an option that don't use jpeg, so It is too much work after all. Also the codes around thumbs are already too complex.

**Comment by step-** [comment]
OK, I understand. Thanks for considering it for awhile.
