### ISSUE TITLE
Request: preserve ownership of dirs and symlinks

### ISSUE THREAD

**Issue by JakeSFR** [jun7/rox-filer#124]
This behavior inherits from the legacy ROX-Filer.
Being a root and copying directories or symlinks preserves their permissions, but not ownership (if other than 'root:root').
Moving preserves them properly, though.
Would it be possible to fix this?

**Comment by jun7** [comment]
Thanks for the report.
What means the legacy ROX-Filer?
And which is your request copy ownership or not?

**Comment by jun7** [comment]
Ah sorry, I didn't notice the title. I see, I will take it.

**Comment by JakeSFR** [comment]
> What means the legacy ROX-Filer?

By "legacy ROX-Filer" I meant the original one:
http://rox.sourceforge.net/desktop/ROX-Filer

> I will take it.

Thank you.
