### ISSUE TITLE
Copy and paste facility (right click menu)

### ISSUE THREAD

**Issue by wdlkmpx** [jun7/rox-filer#136]
I recently read about this fork in the murga forum.  The original rox-filer hasn't been updated since 2005 (http://rox.sourceforge.net/desktop/ROX-Filer)

Well, you know it should be easy to implement if it's not already implemented (haven't tried it).

Most people are used to copy and paste files via keyboard shortcuts and the right click menu.

If this simple feature is implemented, rox wouldn't be as crippled as it is now.. 

I guess you already know how this works,  just try any other file manager, and you'll see that feature already present...

**Comment by jun7** [comment]
Thank you for reporting.

This is fixed by a313dff95f00e70a2e300541a4e2a2ac06565636
