### ISSUE TITLE
Use standard .desktop files in ~/Desktop for ROX pinboard

### ISSUE THREAD

**Issue by wdlkmpx** [jun7/rox-filer#137]
Editing the rox pinboard requires a complex script.. the complexity should be in the rox side.

How about changing the behavior to what we can call "standard".. at least for rox pinboard.

rox should only load what is in ~/Desktop, and optionally it can monitor that directory for changes.. if a file is deleted or added, rox redraws all the icons with the current ~/Desktop contents.. or a special switch can trigger the update..

smplayer.desktop
[Desktop Entry]
Encoding=UTF-8
Name=smplayer
Exec=smplayer
Type=Application
Icon=/usr/share/pixmaps/smplayer.png

name=label
exec=path
icon=icon

I know this change is heavy and requires skills, but it's just a suggestion..

**Comment by frankzen** [comment]
I made this suggestion a couple of months ago. The developer(s) at the time thought it was an idea but would require a lot of work. I too would like to see ROX handling the ~/Desktop files.
