### ISSUE TITLE
copy doesn't preserve folder xattr

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#139]
Enable xattr support in option.
Create a folder and assign some xattr to it.
Add a file to the folder. Assign some xattr to it.
Select folder, right-click, select Copy, enter new folder name, i.e. "copy of", press Enter.
The copy folder includes the file with xattr, but the copy folder itself lost the xattr.
Can you reproduce? commit dec2d36

**Comment by jun7** [comment]
Yes, It is bug. I left it because it is not bad for me ;P
Do you have any broblem with it?

by the way, what is ">commit dec2d36" ?

**Comment by step-** [comment]
Yes, can you fix it, please? Thanks.

> commit ... refers to the commit that I tested to report this bug.

**Comment by jun7** [comment]
All right.

**Comment by jun7** [comment]
Thanks for the report.

**Comment by step-** [comment]
Thank you for fixing it.
