### ISSUE TITLE
dir thumbs

### ISSUE THREAD

**Issue by jun7** [jun7/rox-filer#140]
make first top images of each dirs,
then make 999 images left is good.

**Comment by jun7** [comment]
or a setting max images

**Comment by jun7** [comment]
and don't make it fot light images

**Comment by qubodup** [comment]
It's a cool feature but confusing to me when enabled.

There is also a cross-application effect in GTK+ 2 apps. Even if dir thumbnails are disabled, GTK+ 2 file open/save dialog (Chromium, GIMP, Inkscape) show these thumbnails. Video: https://youtu.be/xTwbPHa9FjE

**Comment by jun7** [comment]
Wow, it is interesting.
Because a dir searches its images is very heavy, so rox makes dir images at times when creating file thumbs.
Hum, not effect in gtk3 ?

**Comment by jun7** [comment]
I get it. If users checked off show dir thumbs then don't create it is good.
I will fix it, thank you for reporting.
