### ISSUE TITLE
Thumbnails generated only for symlinks, not their targets

### ISSUE THREAD

**Issue by JakeSFR** [jun7/rox-filer#142]
If a directory contains an image and a symlink (or symlinks) to it, when you turn on displaying thumbnails, only the (first) symlink gets "thumbnailed", other symlinks and the image itself are not.
It's necessary to disable and enable thumbnails again.

To reproduce:
1. Purge existing thumbnails cache.
2. Go to e.g. ROX-Filer/images dir and turn on thumbnails.

**Comment by jun7** [comment]
Thanks for reporting!

**Comment by JakeSFR** [comment]
Thanks!
