### ISSUE TITLE
Problems with arguments to executables.

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#143]
If I add an argument to an executable file icon on the ROX desktop, I always get the warning "argument added to a non-executable file". For example this morning I added the argument "--password-store=basic" to an icon which calls google-chrome ( it's in /option/google/google-chrome) and I get the warning it can't be done. Same thing if I use the google-chrome.desktop file in /usr/share/applications. 
The only way around this I have found is to call a small script instead of the executable, which is a real problem. Am I doing something wrong or is this a ROX bug?

**Comment by jun7** [comment]
I don't know around it, but if you want to change .desktop files why don't you edit .desktop files? Copy it, Open it As Text and edit the "Exec=" line is normal way I think.

**Comment by frankzen** [comment]
Yes I guess I could do that, but I was wondering why ROX acts the way it does when it's clear it makes provision to run an executable with arguments. But they don't work ?? I wonder whether other people have the same problem.

**Comment by jun7** [comment]
Is it on panel or pinboard? Sorry I don't use those.

**Comment by frankzen** [comment]
The pinboard. Don't use ROX panels.

**Comment by jun7** [comment]
I haven't knowledge of the pinboard.
So I don't know if it was ROX's bug or not. thank you.

**Comment by frankzen** [comment]
I have since discovered ROX requires that it be an actual executable if you want to add parameters to it via a pinboard icon. It won't work with a shell script or a wrapper script. ROX gives the warning parameters added to a non-executable file, even though it may be a shell script which is marked executable.

**Comment by jun7** [comment]
Ah sorry I should close this before. As I said I haven't knowledge of the pinboard.
