### ISSUE TITLE
Click and double click problems

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#145]
Don't know whether this is a bug but if I set Rox options to double click, when I single click on a directory, it opens instead of being marked. I still have to hold down the control key.  However I can mark icons on the pinboard, and files with one click. It's only on directories that single click will open them.

**Comment by frankzen** [comment]
This is on current Rox compiled from zip file downloaded today.

**Comment by jun7** [comment]
It seems work in my env. Which is the option you set?

**Comment by frankzen** [comment]
These:


<?xml version="1.0"?>
<Options>
   <Option name="toolbar_show_info">0</Option>
   <Option name="display_unkn_colour">#000000</Option>
   <Option name="display_show_headers">1</Option>
   <Option name="pinboard_right_margin">0</Option>
   <Option name="pinboard_grid_step">1</Option>
   <Option name="filer_beep_fail">1</Option>
   <Option name="iconify_dir">1</Option>
   <Option name="bind_single_click">1</Option>
   <Option name="blackbox_hack">0</Option>
   <Option name="pinboard_tasklist">0</Option>
   <Option name="pinboard_tasklist_per_workspace">0</Option>
   <Option name="action_delete">1</Option>
   <Option name="display_caps_first">1</Option>
   <Option name="bind_single_pinboard">1</Option>
   <Option name="pinboard_fg_colour">#ffffffffffff</Option>
   <Option name="panel_on_top">0</Option>
   <Option name="panel_obey_workarea">0</Option>
   <Option name="action_link">1</Option>
   <Option name="auto_move">0</Option>
   <Option name="bind_dclick_resizes">1</Option>
   <Option name="display_pipe_colour">#444444</Option>
   <Option name="panel_style">1</Option>
   <Option name="view_alpha">0</Option>
   <Option name="use_background_colour">0</Option>
   <Option name="jpeg_thumbs">1</Option>
   <Option name="toolbar_min_width">0</Option>
   <Option name="bottom_gap">32</Option>
   <Option name="dnd_drag_to_icons">1</Option>
   <Option name="display_cdev_colour">#000000</Option>
   <Option name="menu_quick">1</Option>
   <Option name="create_sub_dir_thumbs">1</Option>
   <Option name="toolbar_disable">gtk-directory, gtk-help</Option>
   <Option name="filer_change_size_num">50</Option>
   <Option name="display_exec_colour">#006000</Option>
   <Option name="display_adir_colour">#006000</Option>
   <Option name="display_colour_types">1</Option>
   <Option name="action_mount">1</Option>
   <Option name="action_mount_command">sudo mount</Option>
   <Option name="action_brief">0</Option>
   <Option name="display_inherit_options">1</Option>
   <Option name="filer_auto_resize">1</Option>
   <Option name="pinboard_image_scaling">1</Option>
   <Option name="panel_width">52</Option>
   <Option name="pinboard_top_margin">0</Option>
   <Option name="pinboard_left_margin">0</Option>
   <Option name="action_newer">0</Option>
   <Option name="pinboard_bg_colour">#093709379ed0</Option>
   <Option name="panel_xinerama">0</Option>
   <Option name="filer_unique_windows">1</Option>
   <Option name="session_pinboard_name">Default</Option>
   <Option name="dnd_left_menu">1</Option>
   <Option name="pinboard_clamp_icons">1</Option>
   <Option name="panel_monitor">0</Option>
   <Option name="display_max_length">0</Option>
   <Option name="bind_new_button_1">0</Option>
   <Option name="display_large_width">250</Option>
   <Option name="dnd_no_hostnames">1</Option>
   <Option name="filer_width_limit">75</Option>
   <Option name="purge_dir_cache">1</Option>
   <Option name="disable_pointer_warp">0</Option>
   <Option name="purge_time">1</Option>
   <Option name="display_icon_size">0</Option>
   <Option name="display_dirs_first">1</Option>
   <Option name="vertical_order_small">0</Option>
   <Option name="display_show_full_type">1</Option>
   <Option name="menu_iconsize">1</Option>
   <Option name="filer_view_type">1</Option>
   <Option name="display_sort_by">0</Option>
   <Option name="dnd_spring_delay">400</Option>
   <Option name="display_bdev_colour">#000000</Option>
   <Option name="dnd_uri_handler">x-terminal-emulator -e wget $1</Option>
   <Option name="window_link">1</Option>
   <Option name="menu_xterm">xterm</Option>
   <Option name="display_show_hidden">1</Option>
   <Option name="dnd_middle_menu">1</Option>
   <Option name="vertical_order_large">0</Option>
   <Option name="display_sock_colour">#ff00ff</Option>
   <Option name="display_err_colour">#ff0000</Option>
   <Option name="panel_is_dock">0</Option>
   <Option name="pinboard_shadow_colour">#18a30d710f56</Option>
   <Option name="display_file_colour">#000000</Option>
   <Option name="filer_size_limit">75</Option>
   <Option name="xattr_show">1</Option>
   <Option name="toolbar_type">2</Option>
   <Option name="action_umount_command">sudo umount</Option>
   <Option name="action_move">1</Option>
   <Option name="session_panel_or_pin">1</Option>
   <Option name="icon_theme">Vista</Option>
   <Option name="filer_beep_multi">1</Option>
   <Option name="thumb_processes_num">3</Option>
   <Option name="pinboard_shadow_labels">1</Option>
   <Option name="label_font">Sans Bold Italic 10</Option>
   <Option name="display_show_dir_thumbs">0</Option>
   <Option name="action_copy">1</Option>
   <Option name="display_door_colour">#ff00ff</Option>
   <Option name="wrap_by_char">0</Option>
   <Option name="panel_avoid">1</Option>
   <Option name="action_eject_command">sudo eject</Option>
   <Option name="pinboard_forward_buttons_13">1</Option>
   <Option name="right_gap">0</Option>
   <Option name="thumb_file_size">128</Option>
   <Option name="action_force">1</Option>
   <Option name="display_dir_colour">#000080</Option>
   <Option name="display_small_width">175</Option>
   <Option name="xattr_ignore">1</Option>
   <Option name="action_recurse">0</Option>
   <Option name="huge_size">128</Option>
   <Option name="pinboard_bottom_margin">0</Option>
   <Option name="iconify_start">1</Option>
   <Option name="override_redirect">1</Option>
   <Option name="display_details">5</Option>
   <Option name="display_show_thumbs">1</Option>
   <Option name="fast_font_calc">1</Option>
   <Option name="filer_short_flag_names">1</Option>
   <Option name="background_colour">#a686b391b746</Option>
   <Option name="dnd_spring_open">1</Option>
</Options>

**Comment by jun7** [comment]
`<Option name="bind_single_click">1</Option>
`
is the option Single-click navigation.
You have to this off.

**Comment by frankzen** [comment]
Whether single click is on or off, in Rox I have to hold down control 
when over a directory if

I want it marked, otherwise the directory opens in Rox.

**Comment by jun7** [comment]
Can you re-post the Options what set the "single click navigation" off.

**Comment by frankzen** [comment]
this is with single click navigation off (unchecked)


<?xml version="1.0"?>
<Options>
   <Option name="toolbar_show_info">0</Option>
   <Option name="display_unkn_colour">#000000</Option>
   <Option name="display_show_headers">1</Option>
   <Option name="pinboard_right_margin">0</Option>
   <Option name="pinboard_grid_step">1</Option>
   <Option name="filer_beep_fail">1</Option>
   <Option name="iconify_dir">1</Option>
   <Option name="bind_single_click">1</Option>
   <Option name="blackbox_hack">0</Option>
   <Option name="pinboard_tasklist">0</Option>
   <Option name="pinboard_tasklist_per_workspace">0</Option>
   <Option name="action_delete">1</Option>
   <Option name="display_caps_first">1</Option>
   <Option name="bind_single_pinboard">0</Option>
   <Option name="pinboard_fg_colour">#ffffffffffff</Option>
   <Option name="panel_on_top">0</Option>
   <Option name="panel_obey_workarea">0</Option>
   <Option name="action_link">1</Option>
   <Option name="auto_move">0</Option>
   <Option name="bind_dclick_resizes">1</Option>
   <Option name="display_pipe_colour">#444444</Option>
   <Option name="panel_style">1</Option>
   <Option name="view_alpha">0</Option>
   <Option name="use_background_colour">0</Option>
   <Option name="jpeg_thumbs">1</Option>
   <Option name="toolbar_min_width">0</Option>
   <Option name="bottom_gap">32</Option>
   <Option name="dnd_drag_to_icons">1</Option>
   <Option name="display_cdev_colour">#000000</Option>
   <Option name="menu_quick">1</Option>
   <Option name="create_sub_dir_thumbs">1</Option>
   <Option name="toolbar_disable">gtk-directory, gtk-help</Option>
   <Option name="filer_change_size_num">50</Option>
   <Option name="display_exec_colour">#006000</Option>
   <Option name="display_adir_colour">#006000</Option>
   <Option name="display_colour_types">1</Option>
   <Option name="action_mount">1</Option>
   <Option name="action_mount_command">sudo mount</Option>
   <Option name="action_brief">0</Option>
   <Option name="display_inherit_options">1</Option>
   <Option name="filer_auto_resize">1</Option>
   <Option name="pinboard_image_scaling">1</Option>
   <Option name="panel_width">52</Option>
   <Option name="pinboard_top_margin">0</Option>
   <Option name="pinboard_left_margin">0</Option>
   <Option name="action_newer">0</Option>
   <Option name="pinboard_bg_colour">#093709379ed0</Option>
   <Option name="panel_xinerama">0</Option>
   <Option name="filer_unique_windows">1</Option>
   <Option name="session_pinboard_name">Default</Option>
   <Option name="dnd_left_menu">1</Option>
   <Option name="pinboard_clamp_icons">1</Option>
   <Option name="panel_monitor">0</Option>
   <Option name="display_max_length">0</Option>
   <Option name="bind_new_button_1">0</Option>
   <Option name="display_large_width">250</Option>
   <Option name="dnd_no_hostnames">1</Option>
   <Option name="filer_width_limit">75</Option>
   <Option name="purge_dir_cache">1</Option>
   <Option name="disable_pointer_warp">0</Option>
   <Option name="purge_time">1</Option>
   <Option name="display_icon_size">0</Option>
   <Option name="display_dirs_first">1</Option>
   <Option name="vertical_order_small">0</Option>
   <Option name="display_show_full_type">1</Option>
   <Option name="menu_iconsize">1</Option>
   <Option name="filer_view_type">1</Option>
   <Option name="display_sort_by">0</Option>
   <Option name="dnd_spring_delay">400</Option>
   <Option name="display_bdev_colour">#000000</Option>
   <Option name="dnd_uri_handler">x-terminal-emulator -e wget $1</Option>
   <Option name="window_link">1</Option>
   <Option name="menu_xterm">xterm</Option>
   <Option name="display_show_hidden">1</Option>
   <Option name="dnd_middle_menu">1</Option>
   <Option name="vertical_order_large">0</Option>
   <Option name="display_sock_colour">#ff00ff</Option>
   <Option name="display_err_colour">#ff0000</Option>
   <Option name="panel_is_dock">0</Option>
   <Option name="pinboard_shadow_colour">#18a30d710f56</Option>
   <Option name="display_file_colour">#000000</Option>
   <Option name="filer_size_limit">75</Option>
   <Option name="xattr_show">1</Option>
   <Option name="toolbar_type">2</Option>
   <Option name="action_umount_command">sudo umount</Option>
   <Option name="action_move">1</Option>
   <Option name="session_panel_or_pin">1</Option>
   <Option name="icon_theme">Vista</Option>
   <Option name="filer_beep_multi">1</Option>
   <Option name="thumb_processes_num">3</Option>
   <Option name="pinboard_shadow_labels">1</Option>
   <Option name="label_font">Sans Bold Italic 10</Option>
   <Option name="display_show_dir_thumbs">0</Option>
   <Option name="action_copy">1</Option>
   <Option name="display_door_colour">#ff00ff</Option>
   <Option name="wrap_by_char">0</Option>
   <Option name="panel_avoid">1</Option>
   <Option name="action_eject_command">sudo eject</Option>
   <Option name="pinboard_forward_buttons_13">1</Option>
   <Option name="right_gap">0</Option>
   <Option name="thumb_file_size">128</Option>
   <Option name="action_force">1</Option>
   <Option name="display_dir_colour">#000080</Option>
   <Option name="display_small_width">175</Option>
   <Option name="xattr_ignore">1</Option>
   <Option name="action_recurse">0</Option>
   <Option name="huge_size">128</Option>
   <Option name="pinboard_bottom_margin">0</Option>
   <Option name="iconify_start">1</Option>
   <Option name="override_redirect">1</Option>
   <Option name="display_details">5</Option>
   <Option name="display_show_thumbs">1</Option>
   <Option name="fast_font_calc">1</Option>
   <Option name="filer_short_flag_names">1</Option>
   <Option name="background_colour">#a686b391b746</Option>
   <Option name="dnd_spring_open">1</Option>
</Options>

**Comment by jun7** [comment]
The option bind_single_click is still On.
Is it only happens with bind_single_click?
Do you set off Single-click navigation?

**Comment by frankzen** [comment]
the is with single click off (unchecked)


<?xml version="1.0"?>
<Options>
   <Option name="toolbar_show_info">0</Option>
   <Option name="display_unkn_colour">#000000</Option>
   <Option name="display_show_headers">1</Option>
   <Option name="pinboard_right_margin">0</Option>
   <Option name="pinboard_grid_step">1</Option>
   <Option name="filer_beep_fail">1</Option>
   <Option name="iconify_dir">1</Option>
   <Option name="bind_single_click">1</Option>
   <Option name="blackbox_hack">0</Option>
   <Option name="pinboard_tasklist">0</Option>
   <Option name="pinboard_tasklist_per_workspace">0</Option>
   <Option name="action_delete">1</Option>
   <Option name="display_caps_first">1</Option>
   <Option name="bind_single_pinboard">0</Option>
   <Option name="pinboard_fg_colour">#ffffffffffff</Option>
   <Option name="panel_on_top">0</Option>
   <Option name="panel_obey_workarea">0</Option>


This is with single click ON (checked)

<?xml version="1.0"?>
<Options>
   <Option name="toolbar_show_info">0</Option>
   <Option name="display_unkn_colour">#000000</Option>
   <Option name="display_show_headers">1</Option>
   <Option name="pinboard_right_margin">0</Option>
   <Option name="pinboard_grid_step">1</Option>
   <Option name="filer_beep_fail">1</Option>
   <Option name="iconify_dir">1</Option>
   <Option name="bind_single_click">1</Option>
   <Option name="blackbox_hack">0</Option>
   <Option name="pinboard_tasklist">0</Option>
   <Option name="pinboard_tasklist_per_workspace">0</Option>
   <Option name="action_delete">1</Option>

So bind_single_click remains at 1 whatever the setting ???

**Comment by frankzen** [comment]
In my case, no matter whether single click is ON or OFF, when i click on a directory in ROX it opens in another filer window.  Single click does allow me to click on the pinboard icons to open a program with one click. Double click also works there with single click OFF...but that is it. Does not work to mark anything in a filer window unless I hold down CTRL.

**Comment by frankzen** [comment]
More info. I downloaded and ran https://github.com/seirios/rox-filer and it acts the same as your version. So you either both have the same bug, or there is something strange with my set-up. I also noticed as you have bind_single_click remains 1 no matter what I have selected. the file options is being saved when I make the change but it always contains bind_single_click=1.

**Comment by jun7** [comment]
Ah you set pinboard's single click option.
The filer's option is not in the pinboard.

**Comment by frankzen** [comment]
Where is the filer option?

**Comment by jun7** [comment]
Options > Filer windows

**Comment by frankzen** [comment]
Thank you. You're right but maybe they should be together? I never even 
saw it before today.

**Comment by jun7** [comment]
No.
