### ISSUE TITLE
Rox strange behavior

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#147]
I am using Rox downloaded as a ZIP file on October 4th and compiled using AppRun. Because I sometimes have to manipulate files in system directories, I setup a launcher to run ROX as root (superuser) this morning. To my surprise, Rox opened my home directory with the icon display on a TRANSPARENT background. My regular Rox launcher ( the desktop is Cinnamon) never does this, matter of fact I don't know how to get a transparent background with Rox!! I don't think this is a bug but I am curious as to why Rox opened with a transparent background.
A second thing which may be a bug, is that after I saved the defaults for the directory using somewhat smaller icons, Rox opens the directory using big icons again. Apparently saving defaults doe not include icon size ??

**Comment by jun7** [comment]
Because default setting has been changed.
Also display settings open without checks, so you have to check it which you want to save.

**Comment by frankzen** [comment]
I still don't understand why Rox filer background is transparent under root, but not under normal user. And I checked ALL the option under saving display style but under root filer still opens with large icons when I saved under smaller icons. Not a big problem. Just more curious than anything. Transparency may be linked to Cinnamon, I will try under Mate which I also have installed.

**Comment by jun7** [comment]
Have you tryed other versions?

**Comment by frankzen** [comment]
This is the first time I have run Rox under root...so I have nothing to compare to. Background also transparent under Mate. Weird thing. So is not saving icon size under root. Unless you have other ideas you can close this.

**Comment by jun7** [comment]
Only icon size? Are not all settings?

**Comment by frankzen** [comment]
Just icon size. If I change the display to list instead of icons and resave when I reopen it opens as list. But icon size remains the same. It looks like icon size if the only thing not being saved under root.

**Comment by jun7** [comment]
Hmm, I couldn't reproduce it.

**Comment by frankzen** [comment]
On 07/10/16 11:21 PM, jun7 wrote:
>
> Hmm, I couldn't reproduce it.
>
> —
>


   Well this morning after my system was suspended overnight, neither can I.
Rox comes up with a regular background, root or user. This is really
strange. I guess this can be closed, except for the inability of Rox to
save icon size, which it does when run as a regular user. Maybe we can 
call it
a "feature", not a bug :)

**Comment by frankzen** [comment]
Additional info on the transparent background. Rox comes up with a transparent background ONLY if icon view is selected. List view gives the regular background according to current theme. If I switch back and forth between icon view and list view background is either transparent or not.

**Comment by jun7** [comment]
Yes, transparent background is only for icon view and panels.
Basicaly my added functions only support icon view.
