### ISSUE TITLE
Have to clean up around the send to

### ISSUE THREAD

**Issue by jun7** [jun7/rox-filer#149]
It is too complex

**Comment by frankzen** [comment]
DL latest version about an hour ago. Scrolling in the ROX window is REALLY slow. One time ROX crashed. Scrolling takes 95% of dual-core cpu.

**Comment by jun7** [comment]
Thank you for reporting!
I couldn't reproduce it, and I changed a lot recently.
So, Is it only Scrolling? which view? details or icons view? which icon size?
memory usage is normal? and is there crash log?

**Comment by jun7** [comment]
53f0778
