### ISSUE TITLE
Scrolling is slow and causes crash

### ISSUE THREAD

**Issue by jun7** [jun7/rox-filer#150]
see #149

**Comment by frankzen** [comment]
First chance I had to try for extended time. Does not seem to depend on whether icon view or list view. Sometime I can enter directory with a lot of files and it won't happen. Another directory with a lot of files and it will happen. Nothing gets logged except normal actions like when I went to options and emptied thumb cache. 

Found this in systemd log when ROX crashed this morning

[54575.205407] ROX-Filer[23462]: segfault at 7edd8bc0 ip 00007fcfa18918c0 sp 00007fffc0f94da0 error 4 in libc-2.24.so[7fcfa181a000+195000]

Weird thing: when the bug surfaces and cpu usage goes to 80% I can stop cpu usage by grabbing
right lower corner of rox window and moving it around screen enlarging and making smaller. While this is going on, cpu usage falls to 6 ot 7 %  ????????

Sorry that's all I have.

**Comment by frankzen** [comment]
Just noticed, when bug is active, list item on toolbar does not respond. Right clicks do not rotate through icon with details etc...until I go up one directory then new display is active.

**Comment by frankzen** [comment]
Just noticed. When bug is active toolbar is unresponsive. Clicking on show/hide icon does not change
display, but indicator above toolbar changes.

**Comment by jun7** [comment]
The directories happening it are fixed? Is it many?

**Comment by frankzen** [comment]
It seems all directories are affected. 

How do I run the debug version ROX-filer.dbg ? Would it help anyway ? I tried changing first line in
AppRun to ROX-filer.dbg and I have gdb installed but no crashes to debug today. Toolbar is still
not responsive when bug surfaces (most of the time). Do you have same behavior on your machine? Or is it just my problem?

**Comment by jun7** [comment]
Instead, which commit causes the bug?
It happens even 'stable' branch?

>Do you have same behavior on your machine?
No.

**Comment by frankzen** [comment]
This "bug" is in the master branch. I always DL the Master branch. Is that not the latest code?

**Comment by jun7** [comment]
Yes the master is latest code.
I want to know which commit causes the bug.

**Comment by frankzen** [comment]
How do I figure that out?

**Comment by jun7** [comment]
move to commit list
   https://github.com/jun7/rox-filer/commits/master
click '<>' on the extreme right of commit.
Then you can download codes of the commit.

**Comment by jun7** [comment]
If you have installed git command,
git clone https://github.com/jun7/rox-filer.git
cd <the dir created, may be ROX-Filer or rox-filer>
git checkout <commit id what left side of the '<>' like '01c30460b4f246d61308f92c54e05f759e4d9235'>
then the dir 'ROX-Filer' in the dir is changed the point of the commit.

**Comment by jun7** [comment]
And so, I suggest you to use git command because you are heavy user of github. (thanks a lot for your contributions).
If you keep the dir created by 'git clone http...' , you can get latest code by only 'git pull' on the dir.
Only make sure you are in master by 'git checkout master'.

**Comment by frankzen** [comment]
Found the first version which gives me problems:

rox-filer-0cfc16e61c856b71aa9fa9f13dbdd0d76e4d41bf

Don't know anything about Git. Installed it but got lost quickly so I just downloaded
Zip files and compiled until I found first version that creates problem.

**Comment by jun7** [comment]
You mean before commit a86f689... is OK and only 0cfc16e... has the bug?

**Comment by frankzen** [comment]
yes

**Comment by frankzen** [comment]
Commit 57f6....is ok all after exhibit the problem on my machine. Sorry about that other message..I lost track at one point.

**Comment by jun7** [comment]
Hmm. the commit only changes menus.
Ah, does it happens with default settings? 
Rename the config dir in .config and even it happens?

**Comment by frankzen** [comment]
Do you mean rename ~/.config/rox.sourceforge.net ?
Why is is still called that...there is no longer a connection to sourceforge ?

**Comment by jun7** [comment]
Yes, ~/.config/rox.sourceforge.net
>Why ...

I don't know.

**Comment by frankzen** [comment]
OK I will try soon. Busy right now with Christmas and holiday stuff.

**Comment by frankzen** [comment]
OK. Latest master version runs fine   **IF** settings.xml  is not in ~/.config/rox.sourceforge.net directory.
Had to experiment to find out which file was screwing it up. I don't know what the difference is between old and new versions but new version does NOT like old version. Long time and a lot of work to find the problem .

**Comment by frankzen** [comment]
Just noticed settings.xml is the file created to remember settings for various directories. As soon as it's created in latest version the slow scroll is back again. I cannot save defaults for any directory without slow scroll coming back.

**Comment by frankzen** [comment]
Sorry settings.xml is NOT the problem. Slow scroll is back. Can't figure out what's going on.Maybe I'll just stay with older version for now. It's got something to do with menu changes I guess.

**Comment by jun7** [comment]
I reproduce it if it only happens on List View.

**Comment by jun7** [comment]
1db3ec64c910ae82dfdc3a7f3c90fb03c13d5490 is the commit

**Comment by jun7** [comment]
Is it fixed?

**Comment by frankzen** [comment]
I will check.

**Comment by frankzen** [comment]
Seems to work just fine...just like it used to :)  Thanks

**Comment by jun7** [comment]
Thank you for reporting!
