### ISSUE TITLE
Empty folders (directories) have weird black background

### ISSUE THREAD

**Issue by qubodup** [jun7/rox-filer#151]
Latest git

This is what an empty folder looks like for me:
![empty folder in rox](https://cloud.githubusercontent.com/assets/18312/21574342/ada193b0-cef1-11e6-86bd-593f5fa62f6a.png)

Perhaps this is failed transparency?

I'm on Arch Linux.

**Comment by jun7** [comment]
It tells what a folder is empty not in loading.
Also it is draggable, so I set something odd pattern to show it is special.

**Comment by qubodup** [comment]
I see, thank you. The dragging functionality is interesting.

I would make this optional and turned off by default, as the visual impression and functionality is very different from a non-empty folder without there being an explanation.

Your decision of course, just a suggestion. Closing this.
