### ISSUE TITLE
Feature request: mouse back/forward buttons

### ISSUE THREAD

**Issue by qubodup** [jun7/rox-filer#152]
My mouse has navigation buttons (forward/back).
![mouse with navigation buttons highlighted](https://cloud.githubusercontent.com/assets/18312/21575431/ef192f3c-cf0b-11e6-97a8-a94246df43cc.jpg)

They work in internet browsers (Chrome) and file browsers (Thunar) but not in ROX. I suggest enabling back/forward functionality for them if it's possible to determine which buttons are back/forward. If not, I suggest to make it possible to the user to enable/disable extra mouse buttons for navigation and to customize which buttons should be back/forward.

Video: https://youtu.be/t00pW9uyiBI

**Comment by jun7** [comment]
Are you using rocker jesture(hold left and right click)?
I think in file manager back button is up in most case and forward button is useless even in web browser.

**Comment by qubodup** [comment]
Sorry, I don't know what a rocker gesture is.

At least to me, this feature is useful in Windows. It exists in Thunar as well for example (video: https://youtu.be/cJ68BQNsem4 ).

I don't think it exists in ROX (only backspace for "go up one level").

It'd be nice to at least be able to use "back" navigation mouse button for "go up one level" in ROX.

**Comment by jun7** [comment]
The rocker jesture is assigned to "go up one level".
You already can go up by 'press'(keep it) left and right click in anywhere of Icon View.

And, I suggest to use Window Link in the case of the video. Scroll free space of the toolbar, double click left if you want into dir, double click right button if you want go up in same positon.

Anyway, assignment "go up one level" to other button is good.
If I get a device having extra buttons I will take it.

**Comment by qubodup** [comment]
I'll be glad to order or pay for a cheap mouse with navigation buttons ( for example from aliexpress.com/item/x/32694138799.html ) qubodup@gmail.com if you're interested :)

**Comment by jun7** [comment]
Thank you, but I have a trackball
http://clearlysuperiortech.com/cst2545-5wproductpage.html
having jacks for external buttons. There is no good button though.

**Comment by jun7** [comment]
Thank you!
