### ISSUE TITLE
Middle mouse button first opens new window but then closes it and navigates original window

### ISSUE THREAD

**Issue by qubodup** [jun7/rox-filer#153]
Apparently this is a new feature: If you press "dir" with middle mouse button (mmb), the first time, a new window opens of that folder.

If you then press with mmb another folder, the new window disappears and the original window navigates into the clicked folder.

This seems inconsistent. Would it be possible to have the option to not create relationships between folders and make mmb just open new windows, controlled by the window manager?

Video: https://youtu.be/oyPGxpELD1w

**Comment by jun7** [comment]
It is named Window Link and Options>Filer Windows>Window behaviour>Window Link.

I have to change the name of options

**Comment by qubodup** [comment]
Thanks! I think "Link windows" or "Window link" is not a bad name, once it is clear what it means.

Here's a screenshot in case others have the same problem:
![settings](https://cloud.githubusercontent.com/assets/18312/21575815/a694675e-cf1a-11e6-9e64-2075ec86f1fc.png)
