### ISSUE TITLE
Can't translate some toolbar labels

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#155]
I created a Gettext .po file just for the toolbar labels. I compile it with `msgfmt` into a .mo file. When I run ROX-Filer with the .mo file installed and the correct LANG= value, all toolbar labels are translated as expected, except for the two labels that are initialized in toolbar.c like this:
```
144   	{N_("Size┼"), GTK_STOCK_ZOOM_IN, N_("Change icon size\n"
184   	{N_("○"), GTK_STOCK_SAVE, N_("Save Current Display Settings...\n"	
```
What do I need to do to be able to translate those two labels like the other ones?

Thank you

**Comment by jun7** [comment]
"Size" is set by display.c - 631
"○": is set by  filer.c - 4343
Ah "○"'s  gettext is currently useless, would you change it?

**Comment by jun7** [comment]
If you want check the initial strings of the toolbtn, it shows when toolbar options changed.

**Comment by step-** [comment]
> "Size" is set by display.c - 631
and can't be localized.
I don't know why, but I'm pretty sure I'm doing localization properly, because it works for all the other toolbar buttons, except for the two I mentioned.

>Ah "○"'s gettext is currently useless, would you change it?
You're saying that the toolbar button shows strings (symbols) that aren't gettexted in the source code. Yes, I  think you should gettext all the strings that are displayed in a button, even if those strings are symbols.

>If you want check the initial strings of the toolbtn, it shows when toolbar options changed.
I'm not sure what you're saying, sorry. "Check the initial strings"... how?

**Comment by jun7** [comment]
Did you even change gettext of display.c - 631?

> I think you should gettext all the strings

Okey, I will fix it.

"the initial strings" are N_("Size┼") and N_("○").
They are over-written but only after changing toolbar option, they are not over-written.

**Comment by step-** [comment]
Yes, those are the strings that I translate in my .po file, but once it's compiled and installed the strings aren't translated.

msgid "Size┼"
msgstr "test 1"

msgid "Size"
msgstr "test 1.1"

msgid "○"
msgstr "test 2"

**Comment by jun7** [comment]
I get it. I will add _() to the "Size" and symbols.

**Comment by jun7** [comment]
If you change the symbols,  please make sure symbol's width are same width, if not the toolbar's width is changed by when state is changed.

**Comment by step-** [comment]
OK, I can translate "Size" with build 7df6634. Thanks.

**Comment by jun7** [comment]
Thank you for reporting.
