### ISSUE TITLE
False "Can't stat directory" with samba share

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#159]
I mount a samba share from my NAS and open it with Rox. Then I unmount the samba share. Rox displays an error message "directory missing/deleted" and closes the list window. So far this is all correct. Then I mount the samba share again and open it with rox. The list window background is red[1], the title bar says "/path/to/mounpoint: Can't stat directory: No such file or directory"[2] **but** the list shows all files and directories in the share. The mountpoint is mounted, valid, and I can navigate through the folders with Rox. The list window background stays red[3] all the time no matter the current folder.
So, three issues, [1], [2], and [3].

**Comment by step-** [comment]
Thank you. I will test and report back.

**Comment by step-** [comment]
Test passed. Thank you for the fix.

**Comment by jun7** [comment]
thank you for reporting!
