### ISSUE TITLE
Right-click menu shifted down when icon is near bottom of screen.

### ISSUE THREAD

**Issue by fatdog64** [jun7/rox-filer#160]
Hi,

I'm one of the Fatdog64 developers. We've been using your fork, and a big thanks for that. One small problem, when you right-click on an icon that's near the bottom of the screen, the right-click menu is shifted down. If the icon is up higher on the screen then no problem. 

![example](https://user-images.githubusercontent.com/2897720/33801415-bdf1472e-dd28-11e7-8a95-172db378b24c.png)

I bisected the problem to:

# git bisect good
51ef72085ecc321b0bed7fd38cf9da2a8edbc46c is the first bad commit
commit 51ef72085ecc321b0bed7fd38cf9da2a8edbc46c
Author: jun7 <jun7@hush.com>
Date:   Thu Dec 15 21:34:23 2016 +0900

    Fix unexpected click of context menu around bottom edge of screen

:040000 040000 22823bdf4967353703e34727b645c9b824a331f0 1dd2429fd9a9c2796fe57dedf6f7de249bb3f009 M	ROX-Filer
#

Let me know if you need any other information. You can try Fatdog64-720 beta if you like, it has the problem. It's here:http://distro.ibiblio.org/fatdog/iso/720b/ 

If you have a linux bootloader installed and a linux partition then all you have to do to install is:
1) Copy vmlinuz and initrd from the iso file to your linux partition.
2) Make a folder named fd64save (or any other name) on your linux partition.
3) Make a bootloader entry. A grub-legacy entry looks like this:

title Fatdog64-720b
  rootnoverify (hd0,2)
  kernel /vmlinuz savefile=direct:device:sda3:/fd64save
  initrd /initrd

Of course you have to replace (hd0,2) and sda3 with whatever you have. Please note the whole OS is in the initrd which is ~360MB, so if you try to use grub-legacy or grub4dos with ext4 partitions the boot will be very slow. Ext3 isn't a problem for those bootloaders.

**Comment by fatdog64** [comment]
Let me try that again, the commit number got mangled. 
51ef72085ecc321b0bed7fd38cf9da2a8edbc46c is the first bad commit.

**Comment by fatdog64** [comment]
Sorry, I guess that's normal.

**Comment by jun7** [comment]
It was for the Options > Menus > File menu on right-click = OFF.
Sorry I had forgotten the option.
The commit makes the consistency (under of the cursor is always Copy is not bad) though yes it is too slow for the file menu.

Thank you for reporting.
