### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#161]
My text color in Rox is purple. How do I change this to white ??? Are you ever going to upgrade Rox to gtk-3 ?

**Comment by frankzen** [comment]
Never mind. It's in options. I have a question about the colors in options. Why are some 6 digits and others 10 digits ???

**Comment by jun7** [comment]
What are the 6 digits and 10 digits? where?

**Comment by frankzen** [comment]
They are scattered through this file:

[options.txt](https://github.com/jun7/rox-filer/files/1565766/options.txt)

**Comment by jun7** [comment]
Gtk's colors have 12 digits in internal. So outputs converted to strings are 12 digits. 6 digits colors are default values may be.
