### ISSUE TITLE
history patch

### ISSUE THREAD

**Issue by tryxan** [jun7/rox-filer#163]
There is this patch for old ROX [http://www.kerofin.demon.co.uk/rox/patch/#history-2.0.0](url) that I use and find very useful. I replaced 'Change to parent in real path' with 'change to previous directory', so it is super fast to navigate up and down directories just using the 'up' icon.

Just thought I would bring it up to you if you missed.

**Comment by jun7** [comment]
Why that replace makes super fast up and down?
I've thought  history back is only useful on miss operation.
What situation / scenarios makes history back useful?

**Comment by tryxan** [comment]
Well I don't have a specific case in mind but I know I use it a lot. Sometimes you have to go back somewhere and clicking 3 or 4 times on the same icon is way faster than clicking each folder one by one. Many things are multi-level organized, websites, sourcecode, cad projects... 
And other filers have it !

**Comment by jun7** [comment]
I want to know specific cases.
Without it, I just suggest to use recently visited menu or middle click the jump.
It is too heavy work, because we have to memory scroll position and icon size or make some logic which messy. Ah it also breaks display settings tree.

**Comment by tryxan** [comment]
Oops Ok... did't even see the middle click jump ! that's exactly the same, nevermind...

**Comment by jun7** [comment]
Anyway, thank you for reporting.
