### ISSUE TITLE
Dragging jpg to gthumb results in a crash

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#165]
Lately whenever I drag a jpg to gthumb, gthumb crashes.

I find this is .xsession-errors

Error: Directory Photo: IFD exceeds data buffer, cannot read next pointer.
libpng error: Not a PNG file

Dragging png's to gthumb is fine.

I am running rox downloaded from here in a zip file on January 18th

**Comment by frankzen** [comment]
Sorry, thought I had replied to this. Yes happens only with ROX, not with file managers in Mate or Cinnamon.

**Comment by frankzen** [comment]
Figured it out. It happens when jpeg for thumbnails is checked in options. Gthumb does not like that.

**Comment by jun7** [comment]
Ah, so gthumb shares thumbnails with rox. Does it also not happen when the Cache File Size is changed?

**Comment by jun7** [comment]
Hmm, if so, only rox if weird.

**Comment by jun7** [comment]
Not dragging. It is caused by shared thumb files. So for backward compatibility, It cannot be fixed. Just disable the jpeg option or change the Cache File Size or use sympath for gthumb.
