### ISSUE TITLE
Dragging a directory to pinboard

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#171]
I am attempting to setup Rox and IceWm in Linux Mint which ia on my other partition.
When I try to drag the directory /usr/share/applications to the pinboard I get a bizarre
message about some of the files being in a different location!! Doing it in Debian Sid using IceWm works fine. Rox is the latest zip file on your repository.

![2018-06-11_155024_859957380](https://user-images.githubusercontent.com/717662/41254005-0fcf32ca-6d90-11e8-9b69-4e0ddbe813a9.png)

Found out I cannot drag any directory which is not in my home to the pinboard. They all give the same
message.

**Comment by frankzen** [comment]
I DL'ed Seirios version compiled it and it runs perfectly. I can drag anything onto the pinboard. There is some difference between your version and his.

**Comment by jun7** [comment]
Only to the pinboard? copying files/make link/move files are fine?

**Comment by jun7** [comment]
Is it fixed?

**Comment by frankzen** [comment]
I'll check tomorrow after I compile and reinstall your version.

**Comment by frankzen** [comment]
Yes, it's fixed. Thank you for your quick action.

**Comment by jun7** [comment]
Thank you for reporting!
