### ISSUE TITLE
Preserving ownership of copied/duplicated files doesn't work anymore.

### ISSUE THREAD

**Issue by JakeSFR** [jun7/rox-filer#179]
I just tried the latest build and noticed that this problem has returned, but this time with regard to files only: https://github.com/jun7/rox-filer/issues/124

In short: while copying or duplicating a file (as root), its original ownership is not preserved and gets set to 'root:root' instead.
It works fine with directories and symlinks, though.

Could you please fix it?

**Comment by jun7** [comment]
Thank you!
