### ISSUE TITLE
'Change sort criteria' crashes ROX

### ISSUE THREAD

**Issue by JakeSFR** [jun7/rox-filer#182]
Some of us (Fatdog devs) have been facing rare, random crashes of recent ROX.
It's hard to tell what could be the trigger, because it happens on various occasions.

In one case dmesg shown:

```
[ 1533.593778] traps: pool[25686] general protection ip:7f9c7c5bf3a4 sp:7f9c6dffa038 error:0 in libfontconfig.so.1.11.1[7f9c7c5a6000+37000]
[ 1533.601742] traps: ROX-Filer[25683] trap int3 ip:7f9c7b6e67fa sp:7ffc31808de0 error:0 in libglib-2.0.so.0.5600.1[7f9c7b686000+12b000]
```

But there was also a case without any info...

Anyway, I just found a way to trigger a crash, but I'm not sure if it's the same one, because it comes from libc, not libglib:

`[15065.150647] ROX-Filer[8011]: segfault at 100000000 ip 00007f0a537ec046 sp 00007ffc4ef74f98 error 4 in libc-2.27.so[7f0a53756000+1b0000]`

Just open a filer window in any directory (can be even empty) and keep clicking 'Change sort criteria' icon using left mouse button.
Crashes every time for me on 6th click.

**Comment by step-** [comment]
I can reproduce it too with those same steps. All open rox windows suddenly disappear but the main ROX-Filer process keeps running in the background.
>Just open a filer window in any directory (can be even empty) and keep clicking 'Change sort criteria' icon using left mouse button.
>Crashes every time for me on 6th click.

**Comment by jun7** [comment]
I confirmed the logic of the bug. Yes it is a simple bug, it just lacks a name of sort type.
Thank you for reporting !

**Comment by JakeSFR** [comment]
> So does the commit fix it ?

Works for me, thanks!

**Comment by step-** [comment]
Works for me, too, thanks.
