### ISSUE TITLE
Enormous thumbnails in Infobox (Properties)

### ISSUE THREAD

**Issue by JakeSFR** [jun7/rox-filer#183]
If an image already has a thumbnail, it's displayed next to the filename in Properties window.
But, if 'Options -> Thumbnails -> Cache File Size' is set to 'Large (256px)' or 'Huge (512px)', the thumbnail is extremely big and often the Properties window exceeds screen limits.

https://imgur.com/a/qbJBzlY

Maybe the size should be scaled to 96x96 or even 64x64?
What do you think?

Btw, I was trying to use gdk_pixbuf_scale_simple, but it won't preserve aspect ratio, so it's a no-go:

thumb=pixmap_try_thumb(path, FALSE);
thumb=gdk_pixbuf_scale_simple(thumb, 96, 96, GDK_INTERP_NEAREST);
if(thumb)

**Comment by jun7** [comment]
I agree.

**Comment by jun7** [comment]
If you thunk up better icon size, please feel free to tell me it.
