### ISSUE TITLE
ROX dies randomly [xcb]

### ISSUE THREAD

**Issue by JakeSFR** [jun7/rox-filer#185]
Some of us (mainly me) have been experiencing rare, random ROX freezes, followed by ROX's quit, without any info in dmesg.

So, I've been running it with '-n' option for a few days and finally got something:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
ROX-Filer: xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

Step (here: step-) has found that this error appears in many places and different apps are affected by it, e.g.:
https://discuss.atom.io/t/atom-over-x11-forwarding-with-xming-errors/25151
https://bugs.launchpad.net/ubuntu/+source/freecad/+bug/1754084

Doesn't seem to be ROX's specific issue, but just letting you know anyway, in case there's anything you can do about it.

**Comment by jun7** [comment]
Thank you for the infomation. I've never met it. I wil keep it in mind.
Ah, Does it happen only slow machine?

**Comment by JakeSFR** [comment]
Thank you.

Well, the machine it happens on is not a speed demon, but can hardly be considered slow (Intel i3), especially with lightweight Linux distro on it. :)

Cheers!

**Comment by jun7** [comment]
Hmm, As long as it happens at random and rare, we have no clue to solve it though freeze and crash very annoys us.
Please tell me if you find any condition. thank you.

**Comment by JakeSFR** [comment]
After weeks of trials and errors first we found a reliable way to reproduce it (continuous clicking on 'Rescan' button) and shortly after this commit in libxcb:

https://cgit.freedesktop.org/xcb/libxcb/commit/?id=fad81b63422105f9345215ab2716c4b804ec7986

After reverting it, we can't reproduce it anymore, so I'm closing this one.

**Comment by jun7** [comment]
Good news. Thank you!
