### ISSUE TITLE
ROX replaces HTML hex codes to ASCII characters

### ISSUE THREAD

**Issue by JakeSFR** [jun7/rox-filer#197]
To reproduce:

1. Create a new file, named e.g. **a%20b%40c**,
2. Right-click that file -> Copy
3. Go to some folder and right-click -> Paste

```
ERROR: No such file or directory
Done - There was one error.
```

Same happens with items sent via right-click to a specific applications.
A script like:

```
#!/bin/sh
echo "$@" > $HOME/rox.log
```

in _/etc/xdg/rox.sourceforge.net/SendTo/.application_x-zerosize_ produces:

`/root/a b@c`

in rox.log.

**Comment by jun7** [comment]
This is not stable. I will test more.

Thank you for reporting!

**Comment by jun7** [comment]
It looks fine.

**Comment by JakeSFR** [comment]
Great, thank you! :)
Works fine now for me, too.

Cheers!
