### ISSUE TITLE
icon size

### ISSUE THREAD

**Issue by jun7** [jun7/rox-filer#20]
It is good that size of small icon depends on font size.
![rox-small-icon](https://cloud.githubusercontent.com/assets/11274072/6878677/9aa0ac1e-d525-11e4-8d9b-6c44e8680769.png)

**Comment by frankzen** [comment]
Yes that's what I was talking about. My observation was that with small icon size set to 18x22  the compile produces an executable which put bigger icons on the screen than the rox-filer that serios has in GIT. I have both and both are set to 18x22...in your version icons on te pinboard are bigger than in his version. I don't understand that. I think there should be a way to change icon size at runtime, like XFCE can and does.

**Comment by jun7** [comment]
I run seirios's version but I can't recognize difference. Also is it possible? that icons on pinboard are small. Aren't large?

**Comment by jun7** [comment]
4ebd80d
