### ISSUE TITLE
Rox sees directory as an executable file.

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#200]
A few weeks ago I dl'ed compiled and installed your literocks version.
Now when I run the regular Rox-Filer, it sees the literocks directory in my home
directory as an executable file. not as a directory.

![Screenshot at 2019-11-24 11-39-53](https://user-images.githubusercontent.com/717662/69497846-5bc62780-0eaf-11ea-80fc-3e36eada8fbb.png)

Literocks sees the directory as a directory.

**Comment by jun7** [comment]
Because literocks has AppRun in the dir as ROX.
I have not changed it. Is there any problem?

**Comment by jun7** [comment]
Because literocks has AppRun in the dir as ROX.
I have not changed it. Is there any problem?

**Comment by frankzen** [comment]
Ahh. OK. Rox sees the AppRun file in the first sub-dir, unlike rox-filer-master which has it one subdir lower.

**Comment by jun7** [comment]
Ah sorry I have changed it. I removed the middle dir.
