### ISSUE TITLE
Why does rox-filer and literocks still have references to sourceforge ?

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#201]
I notice rox-filer still keeps it's config in a directory aimed at the original location of rox on sourceforge. But even the original rox author has moved his stuff to Github. Is there still a need to reference sourceforge ??

Thanks
![Screenshot at 2019-11-25 10-12-58](https://user-images.githubusercontent.com/717662/69552306-3cd99b00-0f6c-11ea-9b3a-b6be1dda1a04.png)

**Comment by jun7** [comment]
I think Github is just for source code. other resources are still on sourceforge even though they are not updated.
Also backward compatiblity.

Has literocks references to sourceforge?

**Comment by frankzen** [comment]
No, no references to sourceforge. 
Yeah Rox on sourceforge hasn't been updated in 8 -10 years!! Most of the added stuff
doesn't work anymore because of new versions of Python etc.
