### ISSUE TITLE
icon for a minimized application window is not the application icon

### ISSUE THREAD

**Issue by drvolk** [jun7/rox-filer#209]
If you minimize an application like firefox the application icon (firefox icon) is displayed as icon of the minmized window within the original rox-filer.

In this fork allways the "default" for minized icons is used for that.
If you have a lot of minimized windows on your desktop it is much easier to find the one you are looking for if it will be represented by its application icon.

**Comment by jun7** [comment]
Thank you for reporting!

**Comment by drvolk** [comment]
Wow, that was a fast fix, thanks !
