### ISSUE TITLE
What happened to Ctrl-X/Cut?

### ISSUE THREAD

**Issue by caoliver** [jun7/rox-filer#210]
I just built from commit eebff777, and Ctrl-X seems to do nothing now.  A git bisection tracks this to commit a313dff9.  What's up with that?

**Comment by jun7** [comment]
It is for cut and paste. 
https://en.wikipedia.org/wiki/Cut,_copy,_and_paste#Cut_and_paste

**Comment by caoliver** [comment]
But cut fails to do anything at all.  At least before it deleted the file.  Now it does absolutely nothing.

**Comment by jun7** [comment]
Couldn't you paste it?

**Comment by caoliver** [comment]
I see what you're saying, but that's very very counterintuitive.  The notion of cut/paste is that _something goes away_, and then you paste it somewhere else.  There is no visual evidence that anything has happened at all.  What happens whet you execute ctrl/x in a CUA based editor?  The selected artifact vanishes, and then appears where you paste it.  Is there some way to simulate this?

**Comment by caoliver** [comment]
I think I can get some useful (at least to me) behavior by adding some shortcuts to menu2.  I'm closing this, though I do believe there should be some visual indication of the cut action.
