### ISSUE TITLE
Multiple folders with .DirIcon files don't refresh anymore

### ISSUE THREAD

**Issue by JakeSFR** [jun7/rox-filer#212]
The problem was introduced with that fix: https://github.com/jun7/rox-filer/commit/b9d0207c6773dd8fa065846545dc8dc1ecdbbb42

To reproduce, create a folder that contains a few folders with .DirIcon inside of each of them and then enter that folder.

Before that commit, all folders refresh instantly:

![1](https://user-images.githubusercontent.com/6226504/83665779-30459780-a5cc-11ea-8df7-3da426af5647.gif)

After that commit, the folders don't refresh automatically, only by clicking the 'Rescan' icon continuously:

![2](https://user-images.githubusercontent.com/6226504/83665795-35a2e200-a5cc-11ea-9c31-24e1013292a0.gif)

**Comment by jun7** [comment]
Ah I forgot it is rendered before the examine.
Thank you for reporting!

**Comment by JakeSFR** [comment]
No worries, thanks for the quick fix!
