### ISSUE TITLE
Installing ROX the "proper" way

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#218]
I have been cloning this repository and running ROX that way for a long time. The problem is all
my references to ROX have to refer to the local ROX repository on my machine (home dir).
My question is this: Is there a way to "install" ROX so the binary and related files end up in
the "proper" directories, that is the ROX binary in /usr/bin, associated files in /usr/share etc etc?

I know I can use the proper ROX package provided by Debian, but it is usually behind this repository, that
is your stuff is usually newer.

**Comment by jun7** [comment]
I don't know.
