### ISSUE TITLE
escape name of file dropped onto rox command line

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#229]
Hi Jun7,

When the `!` command line is active and I click the icon of file `"a '` rox copies `\"a\ \'` to the command line to escape special characters. But when I drag and drop the same icon to the command line special characters aren't escaped.  Please, would it be possible to also escape special characters when I drag and drop an icon to the command line?

Why? Often I want to compare two files located in different folders. So I open two rox windows, one for each folder, then I type `!gvimdiff` and click the file icon in the first rox window, then I drag the second file's icon to the command line in the first window, and press Enter in that window.  If the second file's name includes spaces and other special characters the command fails because the filename isn't shell-escaped properly.

Thank you

![screen-20220624](https://user-images.githubusercontent.com/1414102/175530955-76f829d8-504b-4334-bce4-dc91e076a7e2.png)

https://user-images.githubusercontent.com/1414102/175531023-9466ff9b-6eb2-4178-be74-f31e2ca556b3.mp4

**Comment by jun7** [comment]
Thank you for reporting.
I will fix it.

**Comment by jun7** [comment]
I'm working to fix it. but the drag and drop is built-in feature of the entry widget.
so I have no solution yet.

**Comment by step-** [comment]
Thank you for your update.
