### ISSUE TITLE
Request to disable hyphen at char break

### ISSUE THREAD

**Issue by bkauler** [jun7/rox-filer#232]
In icon-view, with folder or file name underneath, pango from version 1.44.0 introduced a hyphen at character break, which is totally wrong.

Looking at the pango release notes, 1.44.4 made this an opt-out. Hunted for some info on this:

https://docs.gtk.org/Pango/func.attr_insert_hyphens_new.html

https://discourse.gnome.org/t/pango-how-to-turn-off-hyphenation-for-char-wrapping/2101

Could this be implemented in rox-filer, so we go back to display as before 1.44.0?

**Comment by bkauler** [comment]
Good info, shows how it was fixed in nautilus:

https://github.com/mate-desktop/caja/issues/1284

**Comment by jun7** [comment]
Thank you for reporting!
