### ISSUE TITLE
screen freezes when the pop-up window appears , under sway wm

### ISSUE THREAD

**Issue by wxg4net** [jun7/rox-filer#234]
Right-click on the file or folder and select Rename or Properties.
screen freezes when the pop-up window appears 
wm manager: sway

![IMG_20230131_215719](https://user-images.githubusercontent.com/1198284/215788340-9ba89254-4526-4372-be25-81840572065b.jpg)

**Comment by jun7** [comment]
I made sway env on qemu and Not reproduced.
Is there any conditions?
Other x applications work?

**Comment by wxg4net** [comment]
It has been debugged and found that the issue is with Sway rather than Rox.

**Comment by jun7** [comment]
Thank you for reporting!
