### ISSUE TITLE
Rox file name below/under icon rather than right of it

### ISSUE THREAD

**Issue by qubodup** [jun7/rox-filer#40]
When Options/Filer windows/Display's "Default details" is set to anything other than "no details", this will force the text to be on the right of the icon, which especially with long filenames is annoying, especially since "max width" is being ignored.

**Comment by jun7** [comment]
Is it a request to use "max width" with the details ?
And now, right click on the List(chenged from Details) button of the toolbar is assigned to show the details and center is clear. It is  usefull to keep "no details".

**Comment by jun7** [comment]
I've added an option "max length" in commit 8493c70. And now also "max width" of Small Icons will works. Not "stable" though.
I know the best is that the Sizes are being berow of icons, but the Sizes is in the group of the Details and all Details are beside of icons. So I can't change only the Sizes.

**Comment by jun7** [comment]
c7561c3
In huge iconss mode, the details are being below.

**Comment by qubodup** [comment]
Sorry for not replying earlier, yes this is what I meant. The new method is much better!

**Comment by jun7** [comment]
I don't mind it, and I've forgot to say thank you for reporting ;P
