### ISSUE TITLE
File windows too narrow

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#42]
This is a problem I have often had with ROX. The filer windows for directories never open wide enough to include all the fields..I have to expand then to include the last field. Am I setting the defaults wrong??

**Comment by jun7** [comment]
Is it "Options>Filer windows>Largest window size" thing???
How do you set the "Auto-resize filer windows"?
Normally rox should expand automatically to include all items.

**Comment by frankzen** [comment]
Solved my problem with the save function. Now they always open the same.

**Comment by jun7** [comment]
If set auto-resize off, and there are recent items It wills happen.
And home folder has a lot of recent changed items.
