### ISSUE TITLE
How to have each filer window save its own settings.

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#70]
I don't understand if there is a way to have each filer window of directory have it's own settings. I want some to open with name sort, some to open with date sort. Is that possible ?

**Comment by jun7** [comment]
Right click -> Display -> Save Current Display Settings saves sort order.
If you went different settings on same directory, making sym links wills solve it,
because the Display Settings are seved on sym paths.

**Comment by frankzen** [comment]
Seems to work. Had to do middle click however. Right click didn't work.
