### ISSUE TITLE
Not really an issue. Just something I'd like to see

### ISSUE THREAD

**Issue by frankzen** [jun7/rox-filer#97]
I wish there were an easier way to set the backdrop (wallpaper) than right clicking an icon on
the desktop, opening a directory where wallpaper is, and dragging it over, then closing both.

Secondly, I wish ROX used the desktop directory in my home (/home/xxxx/Desktop) . It could then reuse the files which are already there..mostly *.desktop files. As you can see I use ROX mostly
for icons on the desktop. It also annoys me I can't use wallpaper applications such as Nitrogen for some reason. If I could program in c++ or even C I'd do this myself.

I'll leave now :)

**Comment by jun7** [comment]
Did you try the Wallpaper of the site of ROX Desktop?
and
Sorry I can't get what the secondly means.

**Comment by frankzen** [comment]
No I haven't tried that. I will. 

The second point is that ROX keeps it's pinboard data in ~/.config/sourceforge/   as pb_something.

If it read the desktop files in ~/Desktop ( a standard directory in most Linuxes). In my case I also run Mate desktop and that where the information is kept. 
Just a suggestion.
I will try the wallpaper app you suggested.

**Comment by jun7** [comment]
I get it.
Since I don't use pinboard and even desktop,
Probably I will do anything for it but keep it in mind. thank you.

**Comment by frankzen** [comment]
The wallpaper app is not as flexible as Rox background. Different directories for stretched etc etc.
I will stick with Rox system for now.

Thanks

**Comment by jun7** [comment]
The Wallpaper app accept dropped file. so if you placed the app in the send-to dir, setting backdrop is just right clicking of a image file. It can't select style though, editing fixed.py in the app solves it.

**Comment by frankzen** [comment]
OK well then I will try it again. As I said I also have Mate ( like Gnome 2.0) on this system, but I much prefer Roxs pinboard except for the fact the pinboard is a window over the root window. That complicates things for me. Thanks

**Comment by jun7** [comment]
someone else also wanted
#137

**Comment by wdlkmpx** [comment]
I have come to the conclusion that ~/roxdesktop could be a quick solution, it basically works the same as the rox pinboard.xml, but with custom .desktop files, ones that have x= and y=

This way updating the rox desktop becomes easy... a file is installed and uninstalled cleanly, without convoluted post-processing...

Let's say this is the rox pinboard:

	<?xml version="1.0"?>
	<pinboard>
	  <backdrop style="Stretched">/usr/share/backgrounds/default.jpg</backdrop>
	  <icon x="768" y="224" label="trash">/usr/local/apps/Trash</icon>
	  <icon x="768" y="32" label="lock">/usr/local/apps/Xlock</icon>
	  <icon x="32" y="32" label="file">/usr/local/bin/rox</icon>
	  <icon x="160" y="320" label="update">/usr/sbin/update</icon>
	</pinboard>

Rox could just parse text files and look for Field=value

	rox -p [dir]

Example:

~/roxdesktop/.settings
	[settings]
	Backdrop=/usr/share/backgrounds/default.jpg
	Backdrop_style=Streched

~/roxdesktop/trash.desktop
	[Desktop Entry]
	Name=trash
	Exec=/usr/local/apps/Trash
	Icon=/usr/share/pixmaps/trash.png
	x=768
	y=224

~/roxdesktop/lock.desktop
	[Desktop Entry]
	Name=xlock
	Exec=/usr/local/apps/Xlock
	Icon=/usr/share/pixmaps/xlock.png
	x=768
	y=32

etc

it's possible to apply the same logic and add .icon files for the 'globicons stuff'...

**Comment by jun7** [comment]
for tidying
